name: belly_boutique_princess
description: Flutter project app - Bely Boutique Princess.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.1
  firebase_auth: ^3.3.16
  firebase_core: ^1.16.0
  fluttertoast: ^8.0.9
  google_fonts: ^2.3.1
  intl:
  carousel_slider: ^4.1.1
  flutter_services_binding: ^0.1.0
  image_picker: ^0.8.4+9
  firebase_storage: ^10.0.3
  cloud_firestore: ^3.1.14
  uuid: ^3.0.5
  animated_splash_screen: ^1.2.0
  smooth_page_indicator: ^1.0.0+2
  animations: ^2.0.2
  auto_size_text: ^3.0.0
  pinch_zoom: ^1.0.0
  url_launcher: ^6.1.2
  flutter_settings_ui: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/Source_sans_pro/SourceSansProSemiBold.ttf

  assets:
    - assets/images/
    - assets/images/facebook_64.png
    - assets/images/whatsapp_64.png
    - assets/videos/
flutter_intl:
  enabled: true
  main_locale: es
  class_name: S